# Generated by Django 6.0.3 on 2026-05-08 13:17

import uuid

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import course_flow.core.models.user


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('translation_plural', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'cf_discipline',
            },
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('revision_id', models.PositiveIntegerField(default=0, help_text='Monotonic graph revision; incremented on graph-affecting mutations only.')),
            ],
            options={
                'db_table': 'cf_graph',
            },
        ),
        migrations.CreateModel(
            name='Horizontaloutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'db_table': 'cf_horizontaloutcome',
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cf_thread',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('language_preference', models.CharField(choices=[('en-ca', 'En'), ('fr-ca', 'Fr')], default='en-ca', max_length=5)),
                ('notifications_active', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'cf_user',
            },
            managers=[
                ('objects', course_flow.core.models.user.CourseFlowUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('position', models.IntegerField(default=0)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='cf_core.graph')),
                ('thread', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='channel', to='cf_core.thread')),
            ],
            options={
                'db_table': 'cf_channel',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('section_row', models.PositiveIntegerField(help_text='Row index within the section grid (column is channel).')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='cf_core.channel')),
            ],
            options={
                'db_table': 'cf_node',
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_type', models.CharField(blank=True, max_length=64)),
                ('source_port', models.CharField(blank=True, max_length=64)),
                ('target_port', models.CharField(blank=True, max_length=64)),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='cf_core.node')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='cf_core.node')),
            ],
            options={
                'db_table': 'cf_edge',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('message', models.CharField(max_length=1024)),
                ('is_read', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cf_notification',
            },
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='cf_core.graph')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cf_core.outcome')),
            ],
            options={
                'db_table': 'cf_outcome',
            },
        ),
        migrations.CreateModel(
            name='NodeOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cf_core.node')),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cf_core.outcome')),
            ],
            options={
                'db_table': 'cf_node_outcome',
            },
        ),
        migrations.AddField(
            model_name='node',
            name='outcomes',
            field=models.ManyToManyField(blank=True, related_name='nodes', through='cf_core.NodeOutcome', to='cf_core.outcome'),
        ),
        migrations.CreateModel(
            name='HorizontaloutcomeOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horizontal_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horizontal_links', to='cf_core.horizontaloutcome')),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horizontal_link_rows', to='cf_core.outcome')),
            ],
            options={
                'db_table': 'cf_horizontaloutcome_outcome',
            },
        ),
        migrations.AddField(
            model_name='horizontaloutcome',
            name='outcomes',
            field=models.ManyToManyField(blank=True, related_name='horizontal_groups', through='cf_core.HorizontaloutcomeOutcome', to='cf_core.outcome'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_template', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cf_project',
            },
        ),
        migrations.CreateModel(
            name='FavoriteProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_projects', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_links', to='cf_core.project')),
            ],
            options={
                'db_table': 'cf_favorite_project',
            },
        ),
        migrations.CreateModel(
            name='ProjectDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cf_core.discipline')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cf_core.project')),
            ],
            options={
                'db_table': 'cf_project_discipline',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='disciplines',
            field=models.ManyToManyField(blank=True, related_name='projects', through='cf_core.ProjectDiscipline', to='cf_core.discipline'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('position', models.IntegerField(default=0)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='cf_core.graph')),
                ('thread', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='cf_core.thread')),
            ],
            options={
                'db_table': 'cf_section',
            },
        ),
        migrations.AddField(
            model_name='node',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='cf_core.section'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('translation_plural', models.CharField(blank=True, max_length=255)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='cf_core.project')),
            ],
            options={
                'db_table': 'cf_tag',
            },
        ),
        migrations.CreateModel(
            name='OutcomeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cf_core.outcome')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cf_core.tag')),
            ],
            options={
                'db_table': 'cf_outcome_tag',
            },
        ),
        migrations.AddField(
            model_name='outcome',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='outcomes', through='cf_core.OutcomeTag', to='cf_core.tag'),
        ),
        migrations.CreateModel(
            name='NodeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cf_core.node')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cf_core.tag')),
            ],
            options={
                'db_table': 'cf_node_tag',
            },
        ),
        migrations.AddField(
            model_name='node',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='nodes', through='cf_core.NodeTag', to='cf_core.tag'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='cf_core.project')),
            ],
            options={
                'db_table': 'cf_team',
            },
        ),
        migrations.CreateModel(
            name='TeamUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('editor', 'Editor'), ('commenter', 'Commenter'), ('viewer', 'Viewer')], max_length=32)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='cf_core.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cf_team_user',
            },
        ),
        migrations.AddField(
            model_name='outcome',
            name='thread',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='outcome', to='cf_core.thread'),
        ),
        migrations.AddField(
            model_name='node',
            name='thread',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='node', to='cf_core.thread'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cf_core.thread')),
            ],
            options={
                'db_table': 'cf_comment',
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('workflow_type', models.CharField(choices=[('program', 'Program'), ('course', 'Course'), ('activity', 'Activity'), ('task', 'Task')], max_length=8)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_graphs', to=settings.AUTH_USER_MODEL)),
                ('graph', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='cf_core.graph')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='cf_core.project')),
            ],
            options={
                'db_table': 'cf_workflow',
            },
        ),
        migrations.CreateModel(
            name='Taskmeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(blank=True, max_length=1024)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taskmeta', to='cf_core.workflow')),
            ],
            options={
                'db_table': 'cf_taskmeta',
            },
        ),
        migrations.CreateModel(
            name='Programmeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculate_time', models.TextField(blank=True)),
                ('calculate_credits', models.TextField(blank=True)),
                ('calculate_ponderation', models.TextField(blank=True)),
                ('calculate_classification', models.TextField(blank=True)),
                ('classification_general_time', models.DurationField(blank=True, null=True)),
                ('classification_specific_time', models.DurationField(blank=True, null=True)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='programmeta', to='cf_core.workflow')),
            ],
            options={
                'db_table': 'cf_programmeta',
            },
        ),
        migrations.AddField(
            model_name='node',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='cf_core.workflow'),
        ),
        migrations.CreateModel(
            name='Coursemeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(blank=True, max_length=255)),
                ('code', models.CharField(blank=True, max_length=255)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coursemeta', to='cf_core.workflow')),
            ],
            options={
                'db_table': 'cf_coursemeta',
            },
        ),
        migrations.CreateModel(
            name='Activitymeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(blank=True, max_length=1024)),
                ('classification', models.CharField(blank=True, max_length=255)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activitymeta', to='cf_core.workflow')),
            ],
            options={
                'db_table': 'cf_activitymeta',
            },
        ),
        migrations.CreateModel(
            name='Authtoken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authtokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cf_authtoken',
                'indexes': [models.Index(fields=['user', 'revoked_at', 'expires_at'], name='cf_authtoke_user_id_642b0e_idx')],
            },
        ),
        migrations.CreateModel(
            name='FavoriteGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_graphs', to=settings.AUTH_USER_MODEL)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_links', to='cf_core.graph')),
            ],
            options={
                'db_table': 'cf_favorite_graph',
                'constraints': [models.UniqueConstraint(fields=('user', 'graph'), name='cf_favorite_graph_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='nodeoutcome',
            constraint=models.UniqueConstraint(fields=('node', 'outcome'), name='cf_node_outcome_unique'),
        ),
        migrations.AddConstraint(
            model_name='horizontaloutcomeoutcome',
            constraint=models.UniqueConstraint(fields=('horizontal_outcome', 'outcome'), name='cf_horizontaloutcome_outcome_unique'),
        ),
        migrations.AddConstraint(
            model_name='favoriteproject',
            constraint=models.UniqueConstraint(fields=('user', 'project'), name='cf_favorite_project_unique'),
        ),
        migrations.AddConstraint(
            model_name='projectdiscipline',
            constraint=models.UniqueConstraint(fields=('project', 'discipline'), name='cf_project_discipline_unique'),
        ),
        migrations.AddConstraint(
            model_name='outcometag',
            constraint=models.UniqueConstraint(fields=('outcome', 'tag'), name='cf_outcome_tag_unique'),
        ),
        migrations.AddConstraint(
            model_name='nodetag',
            constraint=models.UniqueConstraint(fields=('node', 'tag'), name='cf_node_tag_unique'),
        ),
        migrations.AddConstraint(
            model_name='teamuser',
            constraint=models.UniqueConstraint(fields=('user', 'team'), name='cf_team_user_unique'),
        ),
        migrations.AddConstraint(
            model_name='outcome',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('parent', 'order'), name='cf_outcome_parent_sibling_order_unique'),
        ),
    ]
