# Generated by Django 6.0.3

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cf2_core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflows",
                to="cf2_core.project",
            ),
        ),
    ]
