# Generated by Django 6.0.3

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cf2_core", "0002_workflow_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tags",
                to="cf2_core.project",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="language_preference",
            field=models.CharField(
                choices=[("en-ca", "En-Ca"), ("fr-ca", "Fr-Ca")],
                default="en-ca",
                max_length=5,
            ),
        ),
    ]
