# Generated by Django 6.0.3 on 2026-05-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cf_core', '0003_node_metadata_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='activitymeta',
            name='cf_activitymeta_workflow_xor_node',
        ),
        migrations.RemoveConstraint(
            model_name='coursemeta',
            name='cf_coursemeta_workflow_xor_node',
        ),
        migrations.RemoveConstraint(
            model_name='taskmeta',
            name='cf_taskmeta_workflow_xor_node',
        ),
        migrations.AddConstraint(
            model_name='activitymeta',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('node__isnull', True), ('workflow__isnull', False)), models.Q(('node__isnull', False), ('workflow__isnull', True)), _connector='OR'), name='cf_activitymeta_workflow_xor_node'),
        ),
        migrations.AddConstraint(
            model_name='coursemeta',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('node__isnull', True), ('workflow__isnull', False)), models.Q(('node__isnull', False), ('workflow__isnull', True)), _connector='OR'), name='cf_coursemeta_workflow_xor_node'),
        ),
        migrations.AddConstraint(
            model_name='taskmeta',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('node__isnull', True), ('workflow__isnull', False)), models.Q(('node__isnull', False), ('workflow__isnull', True)), _connector='OR'), name='cf_taskmeta_workflow_xor_node'),
        ),
    ]
