# Generated by Django 6.0.3 on 2026-05-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cf2_core', '0003_tag_project_set_null_user_lang_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language_preference',
            field=models.CharField(choices=[('en-ca', 'En'), ('fr-ca', 'Fr')], default='en-ca', max_length=5),
        ),
    ]
