# Generated by Django 6.0.3 on 2026-05-20 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cf_core', '0010_node_typed_meta_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='linked_workflow',
            field=models.ForeignKey(blank=True, help_text='Optional symbolic link to another library workflow.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes_linked_from', to='cf_core.workflow'),
        ),
        migrations.AlterField(
            model_name='node',
            name='workflow',
            field=models.ForeignKey(help_text='Parent graph workflow for this grid cell (immutable placement context).', on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='cf_core.workflow'),
        ),
    ]
