"""Canonical code-owned discipline catalogue."""

DISCIPLINE_CATALOGUE: tuple[tuple[str, str], ...] = (
    ("anthropology", "Anthropology"),
    ("biology", "Biology"),
    ("business", "Business"),
    ("chemistry", "Chemistry"),
    ("computer_science", "Computer Science"),
    ("design", "Design"),
    ("economics", "Economics"),
    ("engineering", "Engineering"),
    ("english", "English"),
    ("environmental_science", "Environmental Science"),
    ("french", "French"),
    ("geography", "Geography"),
    ("history", "History"),
    ("humanities_general", "Humanities (General)"),
    ("languages", "Languages"),
    ("law", "Law"),
    ("literature", "Literature"),
    ("mathematics", "Mathematics"),
    ("medicine", "Medicine"),
    ("nursing", "Nursing"),
    ("other", "Other"),
    ("performing_arts", "Performing Arts"),
    ("philosophy", "Philosophy"),
    ("physics", "Physics"),
    ("political_science", "Political Science"),
    ("psychology", "Psychology"),
    ("science_general", "Science (General)"),
    ("social_sciences_general", "Social Sciences (General)"),
    ("social_work", "Social Work"),
    ("sociology", "Sociology"),
    ("theology", "Theology"),
    ("visual_arts", "Visual Arts"),
)
