"""Canonical code-owned discipline catalogue."""

DISCIPLINE_CATALOGUE: tuple[str, ...] = (
    "anthropology",
    "biology",
    "business",
    "chemistry",
    "computer_science",
    "design",
    "economics",
    "engineering",
    "english",
    "environmental_science",
    "french",
    "geography",
    "history",
    "humanities_general",
    "languages",
    "law",
    "literature",
    "mathematics",
    "medicine",
    "nursing",
    "other",
    "performing_arts",
    "philosophy",
    "physics",
    "political_science",
    "psychology",
    "science_general",
    "social_sciences_general",
    "social_work",
    "sociology",
    "theology",
    "visual_arts",
)
