from course_flow.views.html import *
from course_flow.views.html.activity import *
from course_flow.views.html.assignment import *
from course_flow.views.html.course import *
from course_flow.views.html.discipline import *
from course_flow.views.html.explore import *
from course_flow.views.html.favorites import *
from course_flow.views.html.home import *
from course_flow.views.html.importer import *
from course_flow.views.html.library import *
from course_flow.views.html.liveProject import *
from course_flow.views.html.program import *
from course_flow.views.html.project import *
from course_flow.views.html.SALTISEAdmin import *
from course_flow.views.html.SALTISEAnalytics import *
from course_flow.views.html.user import *
from course_flow.views.html.workflow import *
from course_flow.views.HTTP.HTTP import *
from course_flow.views.json_api.create_api import *
from course_flow.views.json_api.delete_api import *
from course_flow.views.json_api.duplication_api import *
from course_flow.views.json_api.export_import_api import *
from course_flow.views.json_api.live_project_api import *
from course_flow.views.json_api.menu_api import *
from course_flow.views.json_api.old_courseflow_import_api import *
from course_flow.views.json_api.search_api import *
from course_flow.views.json_api.sharing_api import *
from course_flow.views.json_api.update_api import *
from course_flow.views.json_api.workflow_api import *
