version: '3'

services:
  courseflow-django:
    # platform: linux/amd64
    build:
      context: .
      dockerfile: ./docker/Dockerfile
#    depends_on:
#      db:
#        condition: service_healthy
#        restart: true
#      cache:
#        condition: service_started
    restart: always
    container_name: "courseflow-django"
    shm_size: 2G
    tty: true
    volumes:
      - ./:/app/src
      - ./docker/setup-data.sh:/app/src/setup-data.sh
    ports:
      - "8001:8000"
    networks:
      - cf-network
#        ipv4_address:  10.10.10.7
    entrypoint: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    environment:
      DALITE_DB_NAME: dalite_ng
      DALITE_DB_USER: dalite
      DALITE_DB_PASSWORD: dalite_password123
      DALITE_DB_HOST: db
      DALITE_DB_PORT: 3306
    depends_on:
        db:
          condition: service_healthy

    # use this entrypoint override if the server crashes and we need to debug it
    # entrypoint: ["/bin/bash"]


#  test-data:
#    platform: linux/amd64
#    build:
#      context: .
#      dockerfile: ./docker/Dockerfile
#    restart: on-failure
#    container_name: "courseflow-django-data"
#    shm_size: 2G
#    tty: true
#    volumes:
#      - ./:/app/src
#      - ./docker/setup-data.sh:/app/src/setup-data.sh
#    command: cd /app/src/setup-data.sh
#    depends_on:
#      - courseflow-django
#    networks:
#      - cf-network

  db:
    image: mariadb
    environment:
      # MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: dalite_ng
      MYSQL_USER: dalite
      MYSQL_PASSWORD: dalite_password123
      MYSQL_ROOT_PASSWORD: root_password123
    ports:
      - "3306:3306"
    networks:
      - cf-network
    healthcheck:
      # Use TCP and 127.0.0.1 to avoid socket issues.
      test: ["CMD-SHELL", "mariadb-admin --connect-timeout=3 ping -h '$HOST' -uroot -p$${MYSQL_ROOT_PASSWORD} --protocol=tcp"]
      interval: 5s
      timeout: 3s
      retries: 20

  cache:
    container_name: "cf-redis"
    image: redis:5.0
    restart: always
    ports:
      - '6380:6379'
    command: redis-server --loglevel warning
    networks:
      - cf-network

  helper:
    container_name: "helper"
    image: alpine
    command: sh -c "echo never > /sys/kernel/mm/transparent_hugepage/enabled"
    privileged: true

networks:
  cf-network:
    driver: bridge
#    ipam:
#      config:
#        - subnet: 10.10.10.0/24
