[project]
name = "SALTISE_course_flow"
version = "2.0.0"
description = "CourseFlow"
readme = "README.rst"
authors = []
license = { file = "LICENSE.txt" }
classifiers = [
  "Environment :: Web Environment",
  "Framework :: Django",
  "Framework :: Django :: 3.2",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: BSD License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.8",
  "Topic :: Internet :: WWW/HTTP",
  "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
]
requires-python = ">=3.12"

dependencies = [
  "django",
  "daphne>=4",
  "redislite",
  "djangorestframework-camel-case",
  "drf_spectacular",
  "mysqlclient",
  "xlsxwriter",
  "ruff",
  "celery[redis]>=5.5.3",
  "django-csp>=4.0",
  "django-compressor>=4.5.1",
  "channels>=4.3.1",
  "django-model-utils>=5.0.0",
  "pandas>=2.3.2",
  "django-ratelimit>=4.1.0",
  "bleach>=6.2.0",
  "html2text>=2025.4.15",
]

[dependency-groups]
# Dev / tooling / test-only packages
dev = [
  "isort",
  "pre-commit",
  "pytest-cov",
  "pytest-django",
  "pytest-asyncio",
  "safety",
  "django-debug-toolbar",
  "django-extensions"
]


#[tool.ruff]
#line-length = 200
#target-version = "py312"
#fix = true
#
#[tool.ruff.lint]
#select = ["E", "F", "I", "N", "UP", "B", "TCH", "SIM", "C4", "ERA", "DTZ"]
#ignore = [
#    "TCH001",
#    "TCH002",
#    "TCH003",
#    "F401",
#    "N815",
#    "N999",
#    'ERA001',
#    'SIM108',
#]
#
#[tool.ruff.format]
#quote-style = "double"
#indent-style = "space"



[tool.isort]
skip = ["./course_flow/models/__init__.py"]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 79
