/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check */
        get: operations["course_flow_v2_api_ninja_app_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["listProjects"];
        put?: never;
        /** Create Project */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project/{project_uuid}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project Graph */
        get: operations["getProjectGraph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project/{project_uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["getProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workflows */
        get: operations["listWorkflows"];
        put?: never;
        /** Create Workflow */
        post: operations["createWorkflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflow/{workflow_uuid}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workflow Graph */
        get: operations["getWorkflowGraph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflow/{workflow_uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workflow */
        get: operations["getWorkflow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflow/{workflow_uuid}/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workflow Channels */
        get: operations["listWorkflowChannels"];
        put?: never;
        /** Create Workflow Channel */
        post: operations["createWorkflowChannel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflow/{workflow_uuid}/sections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workflow Sections */
        get: operations["listWorkflowSections"];
        put?: never;
        /** Create Workflow Section */
        post: operations["createWorkflowSection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflow/{workflow_uuid}/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workflow Nodes */
        get: operations["listWorkflowNodes"];
        put?: never;
        /** Create Workflow Node */
        post: operations["createWorkflowNode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflow/{workflow_uuid}/edges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workflow Edges */
        get: operations["listWorkflowEdges"];
        put?: never;
        /** Create Workflow Edge */
        post: operations["createWorkflowEdge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Channel */
        post: operations["createChannel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channel/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Channel */
        get: operations["getChannel"];
        put?: never;
        post?: never;
        /** Delete Channel */
        delete: operations["deleteChannel"];
        options?: never;
        head?: never;
        /** Update Channel */
        patch: operations["updateChannel"];
        trace?: never;
    };
    "/api/section": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Section */
        post: operations["createSection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/section/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Section */
        get: operations["getSection"];
        put?: never;
        post?: never;
        /** Delete Section */
        delete: operations["deleteSection"];
        options?: never;
        head?: never;
        /** Update Section */
        patch: operations["updateSection"];
        trace?: never;
    };
    "/api/node/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Node */
        get: operations["getNode"];
        put?: never;
        post?: never;
        /** Delete Node */
        delete: operations["deleteNode"];
        options?: never;
        head?: never;
        /** Patch Node */
        patch: operations["patchNode"];
        trace?: never;
    };
    "/api/edge/{edge_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Edge */
        get: operations["getEdge"];
        put?: never;
        post?: never;
        /** Delete Edge */
        delete: operations["deleteEdge"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/thread/{uuid}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Thread Comments */
        get: operations["listThreadComments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/me/profile-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Profile Settings */
        get: operations["getMyProfileSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch My Profile Settings */
        patch: operations["patchMyProfileSettings"];
        trace?: never;
    };
    "/api/user/me/notification-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Notification Settings */
        get: operations["getMyNotificationSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch My Notification Settings */
        patch: operations["patchMyNotificationSettings"];
        trace?: never;
    };
    "/api/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/me/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Notifications */
        get: operations["listMyNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/me/notifications/mark-all-as-read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark All My Notifications As Read */
        post: operations["markAllMyNotificationsAsRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/me/notifications/{uuid}/mark-as-read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark One Notification As Read */
        post: operations["markOneNotificationAsRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/me/notifications/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete One Notification */
        delete: operations["deleteOneNotification"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Library */
        post: operations["searchLibrary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** ActivityMetaOut */
        ActivityMetaOut: {
            /**
             * Kind
             * @default activity_meta
             */
            kind: string;
            /** Context */
            context: string;
            /** Classification */
            classification: string;
        };
        /** CourseMetaOut */
        CourseMetaOut: {
            /**
             * Kind
             * @default course_meta
             */
            kind: string;
            /** Classification */
            classification: string;
            /** Code */
            code: string;
        };
        /** ProgramMetaOut */
        ProgramMetaOut: {
            /**
             * Kind
             * @default program_meta
             */
            kind: string;
            /** Calculate Time */
            calculate_time: string;
            /** Calculate Credits */
            calculate_credits: string;
            /** Calculate Ponderation */
            calculate_ponderation: string;
            /** Calculate Classification */
            calculate_classification: string;
            /** Classification General Time */
            classification_general_time?: string | null;
            /** Classification Specific Time */
            classification_specific_time?: string | null;
        };
        /**
         * ProjectDetailOut
         * @description Single project resource: persisted fields only (no related collections).
         */
        ProjectDetailOut: {
            /**
             * Uuid
             * Format: uuid
             */
            uuid: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Is Published */
            is_published: boolean;
            /** Is Template */
            is_template: boolean;
            /** Owner Id */
            owner_id: number;
            /**
             * Date Created
             * Format: date-time
             */
            date_created: string;
            /**
             * Modified On
             * Format: date-time
             */
            modified_on: string;
            /**
             * Workflows
             * @default []
             */
            workflows: components["schemas"]["ProjectWorkflowOut"][];
        };
        /** ProjectWorkflowOut */
        ProjectWorkflowOut: {
            /**
             * Uuid
             * Format: uuid
             */
            uuid: string;
            /** Title */
            title: string;
            /** Owner Id */
            owner_id: number;
            /** Project Id */
            project_id: number | null;
            /** Revision Id */
            revision_id: number;
            /**
             * Date Created
             * Format: date-time
             */
            date_created: string;
            /**
             * Modified On
             * Format: date-time
             */
            modified_on: string;
            unit: components["schemas"]["UnitOut"];
        };
        /** TaskMetaOut */
        TaskMetaOut: {
            /**
             * Kind
             * @default task_meta
             */
            kind: string;
            /** Context */
            context: string;
        };
        /** UnitOut */
        UnitOut: {
            /**
             * Uuid
             * Format: uuid
             */
            uuid: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Unit Type */
            unit_type: string;
            /** Meta */
            meta?: components["schemas"]["TaskMetaOut"] | components["schemas"]["ProgramMetaOut"] | components["schemas"]["CourseMetaOut"] | components["schemas"]["ActivityMetaOut"] | null;
        };
        /** ProjectCreateIn */
        ProjectCreateIn: {
            /** Title */
            title: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Is Published
             * @default false
             */
            is_published: boolean;
            /**
             * Is Template
             * @default false
             */
            is_template: boolean;
        };
        /**
         * ProjectListItemOut
         * @description List rows: compact project fields only.
         */
        ProjectListItemOut: {
            /**
             * Uuid
             * Format: uuid
             */
            uuid: string;
            /** Title */
            title: string;
            /** Owner Id */
            owner_id: number;
            /** Is Published */
            is_published: boolean;
            /** Is Template */
            is_template: boolean;
            /**
             * Modified On
             * Format: date-time
             */
            modified_on: string;
        };
        /** ProjectListMetaOut */
        ProjectListMetaOut: {
            /** Total */
            total: number;
        };
        /** ProjectListOut */
        ProjectListOut: {
            /** Items */
            items: components["schemas"]["ProjectListItemOut"][];
            meta: components["schemas"]["ProjectListMetaOut"];
        };
        /**
         * ProjectGraphProjectionOut
         * @description Project overview: entity fields + workflow UUID references only.
         */
        ProjectGraphProjectionOut: {
            /**
             * Uuid
             * Format: uuid
             */
            uuid: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Is Published */
            is_published: boolean;
            /** Is Template */
            is_template: boolean;
            /** Owner Id */
            owner_id: number;
            /**
             * Date Created
             * Format: date-time
             */
            date_created: string;
            /**
             * Modified On
             * Format: date-time
             */
            modified_on: string;
            /** Workflow Uuids */
            workflow_uuids: string[];
        };
        /** ProjectDetailOutResp */
        ProjectDetailOutResp: {
            item: components["schemas"]["ProjectDetailOut"];
        };
        /**
         * WorkflowDetailOut
         * @description Single workflow resource: persisted fields only (no unit/sections/channels).
         */
        WorkflowDetailOut: {
            /**
             * Uuid
             * Format: uuid
             */
            uuid: string;
            /** Title */
            title: string;
            /** Owner Id */
            owner_id: number;
            /** Project Id */
            project_id: number | null;
            /** Revision Id */
            revision_id: number;
            /**
             * Date Created
             * Format: date-time
             */
            date_created: string;
            /**
             * Modified On
             * Format: date-time
             */
            modified_on: string;
        };
        /**
         * UnitTypeIn
         * @enum {string}
         */
        UnitTypeIn: "program" | "course" | "activity" | "task";
        /** WorkflowCreateIn */
        WorkflowCreateIn: {
            /** Project Id */
            project_id?: number | null;
            /** Workflow Title */
            workflow_title: string;
            /**
             * Unit Title
             * @default
             */
            unit_title: string;
            unit_type: components["schemas"]["UnitTypeIn"];
            /**
             * Unit Description
             * @default
             */
            unit_description: string;
        };
        /**
         * WorkflowListItemOut
         * @description List rows: workflow entity fields only.
         */
        WorkflowListItemOut: {
            /**
             * Uuid
             * Format: uuid
             */
            uuid: string;
            /** Title */
            title: string;
            /** Owner Id */
            owner_id: number;
            /** Project Id */
            project_id: number | null;
            /** Revision Id */
            revision_id: number;
            /**
             * Modified On
             * Format: date-time
             */
            modified_on: string;
        };
        /** WorkflowListMetaOut */
        WorkflowListMetaOut: {
            /** Total */
            total: number;
        };
        /** WorkflowListOut */
        WorkflowListOut: {
            /** Items */
            items: components["schemas"]["WorkflowListItemOut"][];
            meta: components["schemas"]["WorkflowListMetaOut"];
        };
        /** ChannelGraphOut */
        ChannelGraphOut: {
            /**
             * Uuid
             * Format: uuid
             */
            uuid: string;
            /**
             * Workflow Uuid
             * Format: uuid
             */
            workflow_uuid: string;
            /** Title */
            title: string;
            /** Position */
            position: number;
            /** Thread Uuid */
            thread_uuid?: string | null;
        };
        /**
         * EdgeGraphOut
         * @description Endpoints are node UUIDs; ``id`` distinguishes multiple edges between the same pair.
         */
        EdgeGraphOut: {
            /** Id */
            id: number;
            /**
             * Source Node Uuid
             * Format: uuid
             */
            source_node_uuid: string;
            /**
             * Target Node Uuid
             * Format: uuid
             */
            target_node_uuid: string;
            /** Line Type */
            line_type: string;
            /** Source Port */
            source_port: string;
            /** Target Port */
            target_port: string;
        };
        /** NodeGraphOut */
        NodeGraphOut: {
            /**
             * Uuid
             * Format: uuid
             */
            uuid: string;
            /** Section Uuid */
            section_uuid?: string | null;
            /** Channel Uuid */
            channel_uuid?: string | null;
            /** Section Row */
            section_row?: number | null;
            /** Unit Uuid */
            unit_uuid?: string | null;
            /** Thread Uuid */
            thread_uuid?: string | null;
            /** Outcome Uuids */
            outcome_uuids?: string[];
        };
        /** SectionGraphOut */
        SectionGraphOut: {
            /**
             * Uuid
             * Format: uuid
             */
            uuid: string;
            /**
             * Workflow Uuid
             * Format: uuid
             */
            workflow_uuid: string;
            /** Title */
            title: string;
            /** Position */
            position: number;
            /** Thread Uuid */
            thread_uuid?: string | null;
        };
        /** ThreadCommentCountOut */
        ThreadCommentCountOut: {
            /**
             * Thread Uuid
             * Format: uuid
             */
            thread_uuid: string;
            /** Comment Count */
            comment_count: number;
        };
        /**
         * WorkflowGraphMetaOut
         * @description Workflow row + root unit identifiers needed for the editor shell (no nested unit object).
         */
        WorkflowGraphMetaOut: {
            /**
             * Uuid
             * Format: uuid
             */
            uuid: string;
            /** Title */
            title: string;
            /** Owner Id */
            owner_id: number;
            /** Project Id */
            project_id: number | null;
            /** Revision Id */
            revision_id: number;
            /**
             * Date Created
             * Format: date-time
             */
            date_created: string;
            /**
             * Modified On
             * Format: date-time
             */
            modified_on: string;
            /** Root Unit Uuid */
            root_unit_uuid?: string | null;
            /** Root Unit Type */
            root_unit_type?: string | null;
            /**
             * Root Unit Title
             * @default
             */
            root_unit_title: string;
        };
        /**
         * WorkflowGraphOut
         * @description Single round-trip projection for rendering the workflow graph (not nested entity trees).
         */
        WorkflowGraphOut: {
            workflow: components["schemas"]["WorkflowGraphMetaOut"];
            /** Channels */
            channels: components["schemas"]["ChannelGraphOut"][];
            /** Sections */
            sections: components["schemas"]["SectionGraphOut"][];
            /** Nodes */
            nodes: components["schemas"]["NodeGraphOut"][];
            /** Edges */
            edges: components["schemas"]["EdgeGraphOut"][];
            /** Thread Comment Counts */
            thread_comment_counts?: components["schemas"]["ThreadCommentCountOut"][];
        };
        /** WorkflowDetailOutResp */
        WorkflowDetailOutResp: {
            item: components["schemas"]["WorkflowDetailOut"];
        };
        /** ChannelListMetaOut */
        ChannelListMetaOut: {
            /** Total */
            total: number;
        };
        /** ChannelListOut */
        ChannelListOut: {
            /** Items */
            items: components["schemas"]["ChannelOut"][];
            meta: components["schemas"]["ChannelListMetaOut"];
        };
        /** ChannelOut */
        ChannelOut: {
            /**
             * Uuid
             * Format: uuid
             */
            uuid: string;
            /**
             * Workflow Uuid
             * Format: uuid
             */
            workflow_uuid: string;
            /** Title */
            title: string;
            /** Position */
            position: number;
            /** Thread Uuid */
            thread_uuid: string | null;
            /**
             * Date Created
             * Format: date-time
             */
            date_created: string;
            /**
             * Modified On
             * Format: date-time
             */
            modified_on: string;
        };
        /** WorkflowChannelCreateIn */
        WorkflowChannelCreateIn: {
            /** Title */
            title: string;
            /**
             * Position
             * @default 0
             */
            position: number;
            /** Thread Uuid */
            thread_uuid?: string | null;
        };
        /** SectionListMetaOut */
        SectionListMetaOut: {
            /** Total */
            total: number;
        };
        /** SectionListOut */
        SectionListOut: {
            /** Items */
            items: components["schemas"]["SectionOut"][];
            meta: components["schemas"]["SectionListMetaOut"];
        };
        /** SectionOut */
        SectionOut: {
            /**
             * Uuid
             * Format: uuid
             */
            uuid: string;
            /**
             * Workflow Uuid
             * Format: uuid
             */
            workflow_uuid: string;
            /** Title */
            title: string;
            /** Position */
            position: number;
            /** Thread Uuid */
            thread_uuid: string | null;
            /**
             * Date Created
             * Format: date-time
             */
            date_created: string;
            /**
             * Modified On
             * Format: date-time
             */
            modified_on: string;
        };
        /** WorkflowSectionCreateIn */
        WorkflowSectionCreateIn: {
            /** Title */
            title: string;
            /**
             * Position
             * @default 0
             */
            position: number;
            /** Thread Uuid */
            thread_uuid?: string | null;
        };
        /**
         * GraphEdgeMutationOut
         * @description Edge row; ``id`` is the integer PK (``cf2_edge`` has no UUID column).
         */
        GraphEdgeMutationOut: {
            /** Id */
            id: number;
            /**
             * Source Node Uuid
             * Format: uuid
             */
            source_node_uuid: string;
            /**
             * Target Node Uuid
             * Format: uuid
             */
            target_node_uuid: string;
            /** Line Type */
            line_type: string;
            /** Source Port */
            source_port: string;
            /** Target Port */
            target_port: string;
        };
        /** GraphEdgesDeltaOut */
        GraphEdgesDeltaOut: {
            /** Created */
            created: components["schemas"]["GraphEdgeMutationOut"][];
            /** Updated */
            updated: components["schemas"]["GraphEdgeMutationOut"][];
            /** Deleted */
            deleted: number[];
        };
        /** GraphMutationChangesOut */
        GraphMutationChangesOut: {
            nodes: components["schemas"]["GraphNodesDeltaOut"];
            edges: components["schemas"]["GraphEdgesDeltaOut"];
            tags: components["schemas"]["GraphTagsDeltaOut"];
        };
        /** GraphMutationEnvelopeOut */
        GraphMutationEnvelopeOut: {
            /**
             * Workflow Id
             * Format: uuid
             */
            workflow_id: string;
            /** Revision Id */
            revision_id: number;
            changes: components["schemas"]["GraphMutationChangesOut"];
            meta: components["schemas"]["GraphMutationMetaOut"];
        };
        /** GraphMutationMetaOut */
        GraphMutationMetaOut: {
            /** Triggered By */
            triggered_by: string;
            /** Trigger Entity Id */
            trigger_entity_id: string;
        };
        /**
         * GraphNodeMutationOut
         * @description Flat node snapshot for created/updated buckets (aligned with graph read shape).
         */
        GraphNodeMutationOut: {
            /**
             * Uuid
             * Format: uuid
             */
            uuid: string;
            /** Section Uuid */
            section_uuid?: string | null;
            /** Channel Uuid */
            channel_uuid?: string | null;
            /** Section Row */
            section_row?: number | null;
            /** Unit Uuid */
            unit_uuid?: string | null;
            /** Thread Uuid */
            thread_uuid?: string | null;
            /** Outcome Uuids */
            outcome_uuids?: string[];
        };
        /** GraphNodesDeltaOut */
        GraphNodesDeltaOut: {
            /** Created */
            created: components["schemas"]["GraphNodeMutationOut"][];
            /** Updated */
            updated: components["schemas"]["GraphNodeMutationOut"][];
            /** Deleted */
            deleted: string[];
        };
        /**
         * GraphTagStubOut
         * @description Placeholder for future tag mutations; buckets remain empty until implemented.
         */
        GraphTagStubOut: {
            /** Id */
            id: number;
        };
        /** GraphTagsDeltaOut */
        GraphTagsDeltaOut: {
            /** Created */
            created?: components["schemas"]["GraphTagStubOut"][];
            /** Updated */
            updated?: components["schemas"]["GraphTagStubOut"][];
            /** Deleted */
            deleted?: number[];
        };
        /** GraphNodeCreateIn */
        GraphNodeCreateIn: {
            /** Section Uuid */
            section_uuid?: string | null;
            /** Channel Uuid */
            channel_uuid?: string | null;
            /** Section Row */
            section_row?: number | null;
            /** Unit Uuid */
            unit_uuid?: string | null;
        };
        /** GraphEdgeCreateIn */
        GraphEdgeCreateIn: {
            /**
             * Source Node Uuid
             * Format: uuid
             */
            source_node_uuid: string;
            /**
             * Target Node Uuid
             * Format: uuid
             */
            target_node_uuid: string;
            /**
             * Line Type
             * @default
             */
            line_type: string;
            /**
             * Source Port
             * @default
             */
            source_port: string;
            /**
             * Target Port
             * @default
             */
            target_port: string;
        };
        /** ChannelCreateIn */
        ChannelCreateIn: {
            /**
             * Workflow Uuid
             * Format: uuid
             */
            workflow_uuid: string;
            /** Title */
            title: string;
            /**
             * Position
             * @default 0
             */
            position: number;
            /** Thread Uuid */
            thread_uuid?: string | null;
        };
        /** ChannelOutResp */
        ChannelOutResp: {
            item: components["schemas"]["ChannelOut"];
        };
        /** ChannelPatchIn */
        ChannelPatchIn: {
            /** Title */
            title?: string | null;
            /** Position */
            position?: number | null;
            /** Thread Uuid */
            thread_uuid?: string | null;
        };
        /** SectionCreateIn */
        SectionCreateIn: {
            /**
             * Workflow Uuid
             * Format: uuid
             */
            workflow_uuid: string;
            /** Title */
            title: string;
            /**
             * Position
             * @default 0
             */
            position: number;
            /** Thread Uuid */
            thread_uuid?: string | null;
        };
        /** SectionOutResp */
        SectionOutResp: {
            item: components["schemas"]["SectionOut"];
        };
        /** SectionPatchIn */
        SectionPatchIn: {
            /** Title */
            title?: string | null;
            /** Position */
            position?: number | null;
            /** Thread Uuid */
            thread_uuid?: string | null;
        };
        /**
         * GraphNodePatchIn
         * @description Send only fields to change; JSON ``null`` clears nullable FKs / section_row.
         */
        GraphNodePatchIn: {
            /** Section Uuid */
            section_uuid?: string | null;
            /** Channel Uuid */
            channel_uuid?: string | null;
            /** Section Row */
            section_row?: number | null;
            /** Unit Uuid */
            unit_uuid?: string | null;
        };
        /** CommentAuthorOut */
        CommentAuthorOut: {
            /**
             * Uuid
             * Format: uuid
             */
            uuid: string;
            /** Email */
            email: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
        };
        /** CommentOut */
        CommentOut: {
            /**
             * Uuid
             * Format: uuid
             */
            uuid: string;
            /**
             * Thread Uuid
             * Format: uuid
             */
            thread_uuid: string;
            /** Body */
            body: string;
            /**
             * Date Created
             * Format: date-time
             */
            date_created: string;
            /**
             * Modified On
             * Format: date-time
             */
            modified_on: string;
            author: components["schemas"]["CommentAuthorOut"];
        };
        /** LoginOut */
        LoginOut: {
            /** Access Token */
            access_token: string;
            /** Token Type */
            token_type: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            user: components["schemas"]["UserSummaryOut"];
        };
        /** UserSummaryOut */
        UserSummaryOut: {
            /**
             * Uuid
             * Format: uuid
             */
            uuid: string;
            /** Email */
            email: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
        };
        /** LoginIn */
        LoginIn: {
            /** Email */
            email: string;
            /** Password */
            password: string;
            /**
             * Label
             * @default
             */
            label: string;
        };
        /** RegisterIn */
        RegisterIn: {
            /** Email */
            email: string;
            /** Password */
            password: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /**
             * Label
             * @default
             */
            label: string;
        };
        /** LogoutOut */
        LogoutOut: {
            /** Success */
            success: boolean;
        };
        /** UserSummaryOutResp */
        UserSummaryOutResp: {
            item: components["schemas"]["UserSummaryOut"];
        };
        /** UserProfileSettingsOut */
        UserProfileSettingsOut: {
            /**
             * Uuid
             * Format: uuid
             */
            uuid: string;
            /** Email */
            email: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Language Preference */
            language_preference: string;
        };
        /** UserProfileSettingsOutResp */
        UserProfileSettingsOutResp: {
            item: components["schemas"]["UserProfileSettingsOut"];
        };
        /** UserProfileSettingsPatchIn */
        UserProfileSettingsPatchIn: {
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Language Preference */
            language_preference?: string | null;
            /** Email */
            email?: string | null;
        };
        /** UserNotificationSettingsOut */
        UserNotificationSettingsOut: {
            /** Notifications Active */
            notifications_active: boolean;
        };
        /** UserNotificationSettingsOutResp */
        UserNotificationSettingsOutResp: {
            item: components["schemas"]["UserNotificationSettingsOut"];
        };
        /** UserNotificationSettingsPatchIn */
        UserNotificationSettingsPatchIn: {
            /** Notifications Active */
            notifications_active?: boolean | null;
        };
        /** UserListItemOut */
        UserListItemOut: {
            /**
             * Uuid
             * Format: uuid
             */
            uuid: string;
            /** Email */
            email: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
        };
        /** UserListMetaOut */
        UserListMetaOut: {
            /** Total */
            total: number;
        };
        /** UserListOut */
        UserListOut: {
            /** Items */
            items: components["schemas"]["UserListItemOut"][];
            meta: components["schemas"]["UserListMetaOut"];
        };
        /** NotificationItemOut */
        NotificationItemOut: {
            /**
             * Uuid
             * Format: uuid
             */
            uuid: string;
            /** Message */
            message: string;
            /** Is Read */
            is_read: boolean;
            /**
             * Date Created
             * Format: date-time
             */
            date_created: string;
        };
        /** NotificationListMetaOut */
        NotificationListMetaOut: {
            /** Total */
            total: number;
            /** Unread Count */
            unread_count: number;
        };
        /** NotificationListOut */
        NotificationListOut: {
            /** Items */
            items: components["schemas"]["NotificationItemOut"][];
            meta: components["schemas"]["NotificationListMetaOut"];
        };
        /** NotificationsMarkAllAsReadMetaOut */
        NotificationsMarkAllAsReadMetaOut: {
            /** Updated Count */
            updated_count: number;
            /** Unread Count */
            unread_count: number;
        };
        /** NotificationsMarkAllAsReadOut */
        NotificationsMarkAllAsReadOut: {
            meta: components["schemas"]["NotificationsMarkAllAsReadMetaOut"];
        };
        /** NotificationItemOutResp */
        NotificationItemOutResp: {
            item: components["schemas"]["NotificationItemOut"];
        };
        /** LibraryItemOut */
        LibraryItemOut: {
            /** Object Type */
            object_type: string;
            /** Uuid */
            uuid?: string | null;
            /** Workflow Uuid */
            workflow_uuid?: string | null;
            /** Project Uuid */
            project_uuid?: string | null;
            /** Unit Uuid */
            unit_uuid?: string | null;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /**
             * Date Created
             * Format: date-time
             */
            date_created: string;
            /**
             * Modified On
             * Format: date-time
             */
            modified_on: string;
            /** Is Template */
            is_template: boolean;
            /** Is Favorite */
            is_favorite: boolean;
        };
        /** LibraryMetaOut */
        LibraryMetaOut: {
            /** Total Results */
            total_results: number;
            /** Page Count */
            page_count: number;
            /** Current Page */
            current_page: number;
            /** Results Per Page */
            results_per_page: number;
        };
        /** LibrarySearchOut */
        LibrarySearchOut: {
            /** Items */
            items: components["schemas"]["LibraryItemOut"][];
            meta: components["schemas"]["LibraryMetaOut"];
        };
        /** LibraryFilterIn */
        LibraryFilterIn: {
            /** Name */
            name: string;
            /** Value */
            value: unknown;
        };
        /** LibraryPaginationIn */
        LibraryPaginationIn: {
            /**
             * Page
             * @default 0
             */
            page: number;
            /**
             * Results Per Page
             * @default 10
             */
            results_per_page: number;
        };
        /** LibrarySearchIn */
        LibrarySearchIn: {
            pagination?: components["schemas"]["LibraryPaginationIn"] | null;
            sort?: components["schemas"]["LibrarySortIn"] | null;
            /** Filters */
            filters?: components["schemas"]["LibraryFilterIn"][] | null;
        };
        /**
         * LibrarySortDirectionIn
         * @enum {string}
         */
        LibrarySortDirectionIn: "ASC" | "DESC";
        /** LibrarySortIn */
        LibrarySortIn: {
            /** @default DATE_CREATED */
            value: components["schemas"]["LibrarySortValueIn"];
            /** @default DESC */
            direction: components["schemas"]["LibrarySortDirectionIn"];
        };
        /**
         * LibrarySortValueIn
         * @enum {string}
         */
        LibrarySortValueIn: "DATE_CREATED" | "DATE_MODIFIED" | "A_Z";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    course_flow_v2_api_ninja_app_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectListOut"];
                };
            };
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreateIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetailOut"];
                };
            };
        };
    };
    getProjectGraph: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectGraphProjectionOut"];
                };
            };
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetailOutResp"];
                };
            };
        };
    };
    listWorkflows: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowListOut"];
                };
            };
        };
    };
    createWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowCreateIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDetailOut"];
                };
            };
        };
    };
    getWorkflowGraph: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowGraphOut"];
                };
            };
        };
    };
    getWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDetailOutResp"];
                };
            };
        };
    };
    listWorkflowChannels: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelListOut"];
                };
            };
        };
    };
    createWorkflowChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowChannelCreateIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelOut"];
                };
            };
        };
    };
    listWorkflowSections: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectionListOut"];
                };
            };
        };
    };
    createWorkflowSection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowSectionCreateIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectionOut"];
                };
            };
        };
    };
    listWorkflowNodes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeGraphOut"][];
                };
            };
        };
    };
    createWorkflowNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GraphNodeCreateIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphMutationEnvelopeOut"];
                };
            };
        };
    };
    listWorkflowEdges: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EdgeGraphOut"][];
                };
            };
        };
    };
    createWorkflowEdge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GraphEdgeCreateIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphMutationEnvelopeOut"];
                };
            };
        };
    };
    createChannel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChannelCreateIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelOut"];
                };
            };
        };
    };
    getChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelOutResp"];
                };
            };
        };
    };
    deleteChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChannelPatchIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelOutResp"];
                };
            };
        };
    };
    createSection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SectionCreateIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectionOut"];
                };
            };
        };
    };
    getSection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectionOutResp"];
                };
            };
        };
    };
    deleteSection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateSection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SectionPatchIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectionOutResp"];
                };
            };
        };
    };
    getNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeGraphOut"];
                };
            };
        };
    };
    deleteNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphMutationEnvelopeOut"];
                };
            };
        };
    };
    patchNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GraphNodePatchIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphMutationEnvelopeOut"];
                };
            };
        };
    };
    getEdge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                edge_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EdgeGraphOut"];
                };
            };
        };
    };
    deleteEdge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                edge_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphMutationEnvelopeOut"];
                };
            };
        };
    };
    listThreadComments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentOut"][];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginOut"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginOut"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutOut"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSummaryOutResp"];
                };
            };
        };
    };
    getMyProfileSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileSettingsOutResp"];
                };
            };
        };
    };
    patchMyProfileSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserProfileSettingsPatchIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileSettingsOutResp"];
                };
            };
        };
    };
    getMyNotificationSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserNotificationSettingsOutResp"];
                };
            };
        };
    };
    patchMyNotificationSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserNotificationSettingsPatchIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserNotificationSettingsOutResp"];
                };
            };
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListOut"];
                };
            };
        };
    };
    listMyNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationListOut"];
                };
            };
        };
    };
    markAllMyNotificationsAsRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationsMarkAllAsReadOut"];
                };
            };
        };
    };
    markOneNotificationAsRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationItemOutResp"];
                };
            };
        };
    };
    deleteOneNotification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    searchLibrary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LibrarySearchIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibrarySearchOut"];
                };
            };
        };
    };
}
