# Generated by Django 2.2.6 on 2019-10-16 20:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('course_flow_creation_distribution', '0002_auto_20191016_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='hash',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
