# Generated by Django 2.2.6 on 2019-10-16 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("course_flow_creation_distribution", "0003_week_hash")]

    operations = [
        migrations.RemoveConstraint(model_name="nodestrategy", name="ranking")
    ]
