# Generated by Django 2.2.6 on 2019-10-17 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("course_flow_creation_distribution", "0005_auto_20191017_1843")]

    operations = [
        migrations.RemoveConstraint(
            model_name="componentweek", name="component_ranking"
        ),
        migrations.RemoveConstraint(model_name="nodestrategy", name="node_ranking"),
        migrations.RemoveConstraint(
            model_name="strategyactivity", name="strategy_ranking"
        ),
        migrations.RemoveConstraint(model_name="weekcourse", name="week_ranking"),
    ]
