import { SliceNamespace, StrategyActions } from '@cfRedux/types/enumActions'
import { TStrategy } from '@cfRedux/types/type'
import { PayloadAction, createSlice } from '@reduxjs/toolkit'

interface ToggleStrategyPayload {
  isStrategy: boolean
  strategy: TStrategy
}

const initialState: TStrategy[] = []

const strategySlice = createSlice({
  name: SliceNamespace.STRATEGY,
  initialState,
  reducers: {
    toggleStrategy(state, action: PayloadAction<ToggleStrategyPayload>) {
      if (action.payload.isStrategy) {
        state.push(action.payload.strategy)
      }
    }
  }
})

// Export the action creators automatically generated by createSlice
export const { toggleStrategy: strategyToggleStrategy } = strategySlice.actions

// Export the reducer
export default strategySlice.reducer
