# Generated by Django 6.0.3 on 2026-03-25 01:33

import uuid

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import course_flow_v2.core.models.user


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('position', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'cf2_channel',
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('translation_plural', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'cf2_discipline',
            },
        ),
        migrations.CreateModel(
            name='HorizontalOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'db_table': 'cf2_horizontal_outcome',
            },
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'db_table': 'cf2_outcome',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('position', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'cf2_section',
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cf2_thread',
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('workflow_type', models.CharField(choices=[('program', 'Program'), ('course', 'Course'), ('activity', 'Activity'), ('task', 'Task')], max_length=32)),
            ],
            options={
                'db_table': 'cf2_workflow',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'cf2_user',
            },
            managers=[
                ('objects', course_flow_v2.core.models.user.CourseFlowUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='cf2_core.channel')),
            ],
            options={
                'db_table': 'cf2_node',
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_type', models.CharField(blank=True, max_length=64)),
                ('source_port', models.CharField(blank=True, max_length=64)),
                ('target_port', models.CharField(blank=True, max_length=64)),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='cf2_core.node')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='cf2_core.node')),
            ],
            options={
                'db_table': 'cf2_edge',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('message', models.CharField(max_length=1024)),
                ('is_read', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cf2_notification',
            },
        ),
        migrations.CreateModel(
            name='NodeOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cf2_core.node')),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cf2_core.outcome')),
            ],
            options={
                'db_table': 'cf2_node_outcome',
            },
        ),
        migrations.AddField(
            model_name='node',
            name='outcomes',
            field=models.ManyToManyField(blank=True, related_name='nodes', through='cf2_core.NodeOutcome', to='cf2_core.outcome'),
        ),
        migrations.CreateModel(
            name='HorizontalOutcomeOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horizontal_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horizontal_links', to='cf2_core.horizontaloutcome')),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horizontal_link_rows', to='cf2_core.outcome')),
            ],
            options={
                'db_table': 'cf2_horizontal_outcome_outcome',
            },
        ),
        migrations.AddField(
            model_name='horizontaloutcome',
            name='outcomes',
            field=models.ManyToManyField(blank=True, related_name='horizontal_groups', through='cf2_core.HorizontalOutcomeOutcome', to='cf2_core.outcome'),
        ),
        migrations.CreateModel(
            name='OutcomeOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_links_from', to='cf2_core.outcome')),
                ('to_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_links_to', to='cf2_core.outcome')),
            ],
            options={
                'db_table': 'cf2_outcome_outcome',
            },
        ),
        migrations.AddField(
            model_name='outcome',
            name='parent_outcomes',
            field=models.ManyToManyField(related_name='child_outcomes', through='cf2_core.OutcomeOutcome', through_fields=('from_outcome', 'to_outcome'), to='cf2_core.outcome'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_template', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cf2_project',
            },
        ),
        migrations.CreateModel(
            name='FavoriteProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_projects', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_links', to='cf2_core.project')),
            ],
            options={
                'db_table': 'cf2_favorite_project',
            },
        ),
        migrations.CreateModel(
            name='ProjectDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cf2_core.discipline')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cf2_core.project')),
            ],
            options={
                'db_table': 'cf2_project_discipline',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='disciplines',
            field=models.ManyToManyField(blank=True, related_name='projects', through='cf2_core.ProjectDiscipline', to='cf2_core.discipline'),
        ),
        migrations.CreateModel(
            name='ProjectTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='cf2_core.project')),
            ],
            options={
                'db_table': 'cf2_project_team',
            },
        ),
        migrations.CreateModel(
            name='ProjectTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectteam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='cf2_core.projectteam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectteam_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cf2_project_team_member',
            },
        ),
        migrations.AddField(
            model_name='node',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='cf2_core.section'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('translation_plural', models.CharField(blank=True, max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='cf2_core.project')),
            ],
            options={
                'db_table': 'cf2_tag',
            },
        ),
        migrations.CreateModel(
            name='OutcomeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cf2_core.outcome')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cf2_core.tag')),
            ],
            options={
                'db_table': 'cf2_outcome_tag',
            },
        ),
        migrations.AddField(
            model_name='outcome',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='outcomes', through='cf2_core.OutcomeTag', to='cf2_core.tag'),
        ),
        migrations.CreateModel(
            name='NodeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cf2_core.node')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cf2_core.tag')),
            ],
            options={
                'db_table': 'cf2_node_tag',
            },
        ),
        migrations.AddField(
            model_name='node',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='nodes', through='cf2_core.NodeTag', to='cf2_core.tag'),
        ),
        migrations.AddField(
            model_name='section',
            name='thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section', to='cf2_core.thread'),
        ),
        migrations.AddField(
            model_name='outcome',
            name='thread',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='outcome', to='cf2_core.thread'),
        ),
        migrations.AddField(
            model_name='node',
            name='thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='node', to='cf2_core.thread'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cf2_core.thread')),
            ],
            options={
                'db_table': 'cf2_comment',
            },
        ),
        migrations.AddField(
            model_name='channel',
            name='thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel', to='cf2_core.thread'),
        ),
        migrations.CreateModel(
            name='TaskMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(blank=True, max_length=1024)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_meta', to='cf2_core.workflow')),
            ],
            options={
                'db_table': 'cf2_task_meta',
            },
        ),
        migrations.CreateModel(
            name='ProgramMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculate_time', models.TextField(blank=True)),
                ('calculate_credits', models.TextField(blank=True)),
                ('calculate_ponderation', models.TextField(blank=True)),
                ('calculate_classification', models.TextField(blank=True)),
                ('classification_general_time', models.DurationField(blank=True, null=True)),
                ('classification_specific_time', models.DurationField(blank=True, null=True)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='program_meta', to='cf2_core.workflow')),
            ],
            options={
                'db_table': 'cf2_program_meta',
            },
        ),
        migrations.AddField(
            model_name='node',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='cf2_core.workflow'),
        ),
        migrations.CreateModel(
            name='CourseMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(blank=True, max_length=255)),
                ('code', models.CharField(blank=True, max_length=255)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_meta', to='cf2_core.workflow')),
            ],
            options={
                'db_table': 'cf2_course_meta',
            },
        ),
        migrations.CreateModel(
            name='ActivityMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(blank=True, max_length=1024)),
                ('classification', models.CharField(blank=True, max_length=255)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity_meta', to='cf2_core.workflow')),
            ],
            options={
                'db_table': 'cf2_activity_meta',
            },
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_graphs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='graphs', to='cf2_core.project')),
            ],
            options={
                'db_table': 'cf2_graph',
            },
        ),
        migrations.AddField(
            model_name='workflow',
            name='graph',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='cf2_core.graph'),
        ),
        migrations.AddField(
            model_name='section',
            name='graph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='cf2_core.graph'),
        ),
        migrations.AddField(
            model_name='outcome',
            name='graph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='cf2_core.graph'),
        ),
        migrations.CreateModel(
            name='FavoriteGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_graphs', to=settings.AUTH_USER_MODEL)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_links', to='cf2_core.graph')),
            ],
            options={
                'db_table': 'cf2_favorite_graph',
            },
        ),
        migrations.AddField(
            model_name='channel',
            name='graph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='cf2_core.graph'),
        ),
        migrations.AddConstraint(
            model_name='nodeoutcome',
            constraint=models.UniqueConstraint(fields=('node', 'outcome'), name='cf2_node_outcome_unique'),
        ),
        migrations.AddConstraint(
            model_name='horizontaloutcomeoutcome',
            constraint=models.UniqueConstraint(fields=('horizontal_outcome', 'outcome'), name='cf2_horizontal_outcome_outcome_unique'),
        ),
        migrations.AddConstraint(
            model_name='outcomeoutcome',
            constraint=models.UniqueConstraint(fields=('from_outcome', 'to_outcome'), name='cf2_outcome_outcome_unique_pair'),
        ),
        migrations.AddConstraint(
            model_name='favoriteproject',
            constraint=models.UniqueConstraint(fields=('user', 'project'), name='cf2_favorite_project_unique'),
        ),
        migrations.AddConstraint(
            model_name='projectdiscipline',
            constraint=models.UniqueConstraint(fields=('project', 'discipline'), name='cf2_project_discipline_unique'),
        ),
        migrations.AddConstraint(
            model_name='projectteammember',
            constraint=models.UniqueConstraint(fields=('user', 'projectteam'), name='cf2_project_team_member_unique'),
        ),
        migrations.AddConstraint(
            model_name='outcometag',
            constraint=models.UniqueConstraint(fields=('outcome', 'tag'), name='cf2_outcome_tag_unique'),
        ),
        migrations.AddConstraint(
            model_name='nodetag',
            constraint=models.UniqueConstraint(fields=('node', 'tag'), name='cf2_node_tag_unique'),
        ),
        migrations.AddConstraint(
            model_name='favoritegraph',
            constraint=models.UniqueConstraint(fields=('user', 'graph'), name='cf2_favorite_graph_unique'),
        ),
    ]
