# Generated by Django 6.0.3 on 2026-03-27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cf2_core", "0002_authtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="section_row",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Row index within the section grid (column is channel).",
                null=True,
            ),
        ),
    ]
