# Generated by Django 6.0.3 on 2026-03-30 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cf2_core', '0005_workflow_revision_id'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='authtoken',
            new_name='cf2_auth_to_user_id_472ff9_idx',
            old_name='cf2_auth_to_user_id_39f7fa_idx',
        ),
    ]
