# Generated by Django 6.0.3 on 2026-03-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cf2_core', '0006_rename_cf2_auth_to_user_id_39f7fa_idx_cf2_auth_to_user_id_472ff9_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language_preference',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', max_length=8),
        ),
        migrations.AddField(
            model_name='user',
            name='notifications_active',
            field=models.BooleanField(default=False),
        ),
    ]
