# Generated by Django 6.0.3 on 2026-04-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cf2_core', '0007_user_language_preference_user_notifications_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectteammember',
            name='role',
            field=models.CharField(choices=[('editor', 'Editor'), ('commenter', 'Commenter'), ('viewer', 'Viewer')], default='viewer', max_length=32),
        ),
    ]
