# Generated by Django 2.2.9 on 2020-02-19 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("course_flow", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
            },
        ),
        migrations.AlterModelOptions(
            name="componentprogram",
            options={
                "verbose_name": "Component-Program Link",
                "verbose_name_plural": "Component-Program Links",
            },
        ),
        migrations.AlterModelOptions(
            name="componentweek",
            options={
                "verbose_name": "Component-Week Link",
                "verbose_name_plural": "Component-Week Links",
            },
        ),
        migrations.AlterModelOptions(
            name="nodestrategy",
            options={
                "verbose_name": "Node-Strategy Link",
                "verbose_name_plural": "Node-Strategy Links",
            },
        ),
        migrations.AlterModelOptions(
            name="outcome",
            options={
                "verbose_name": "Outcome",
                "verbose_name_plural": "Outcomes",
            },
        ),
        migrations.AlterModelOptions(
            name="outcomeactivity",
            options={
                "verbose_name": "Outcome-Activity Link",
                "verbose_name_plural": "Outcome-Activity Links",
            },
        ),
        migrations.AlterModelOptions(
            name="outcomeartifact",
            options={
                "verbose_name": "Outcome-Artifact Link",
                "verbose_name_plural": "Outcome-Artifact Links",
            },
        ),
        migrations.AlterModelOptions(
            name="outcomeassesment",
            options={
                "verbose_name": "Outcome-Assesment Link",
                "verbose_name_plural": "Outcome-Assesment Links",
            },
        ),
        migrations.AlterModelOptions(
            name="outcomecourse",
            options={
                "verbose_name": "Outcome-Course Link",
                "verbose_name_plural": "Outcome-Course Links",
            },
        ),
        migrations.AlterModelOptions(
            name="outcomenode",
            options={
                "verbose_name": "Outcome-Node Link",
                "verbose_name_plural": "Outcome-Node Links",
            },
        ),
        migrations.AlterModelOptions(
            name="outcomepreparation",
            options={
                "verbose_name": "Outcome-Preparation Link",
                "verbose_name_plural": "Outcome-Preparation Links",
            },
        ),
        migrations.AlterModelOptions(
            name="outcomeprogram",
            options={
                "verbose_name": "Outcome-Program Link",
                "verbose_name_plural": "Outcome-Program Links",
            },
        ),
        migrations.AlterModelOptions(
            name="outcomestrategy",
            options={
                "verbose_name": "Outcome-Strategy Link",
                "verbose_name_plural": "Outcome-Strategy Links",
            },
        ),
        migrations.AlterModelOptions(
            name="outcomeweek",
            options={
                "verbose_name": "Outcome-Week Link",
                "verbose_name_plural": "Outcome-Week Links",
            },
        ),
        migrations.AlterModelOptions(
            name="strategy",
            options={
                "verbose_name": "Strategy",
                "verbose_name_plural": "Strategies",
            },
        ),
        migrations.AlterModelOptions(
            name="strategyactivity",
            options={
                "verbose_name": "Strategy-Activity Link",
                "verbose_name_plural": "Strategy-Activity Links",
            },
        ),
        migrations.AlterModelOptions(
            name="weekcourse",
            options={
                "verbose_name": "Week-Course Link",
                "verbose_name_plural": "Week-Course Links",
            },
        ),
        migrations.AddField(
            model_name="activity",
            name="static",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="course",
            name="static",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="node",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="author",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="NodeCompletionStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course_flow.Node",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Node Completion Status",
                "verbose_name_plural": "Node Completion Statuses",
            },
        ),
        migrations.CreateModel(
            name="ComponentCompletionStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course_flow.Component",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Component Completion Status",
                "verbose_name_plural": "Component Completion Statuses",
            },
        ),
        migrations.AddField(
            model_name="node",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                related_name="students",
                through="course_flow.NodeCompletionStatus",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
