# Generated by Django 2.2.9 on 2020-02-26 21:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("course_flow", "0003_auto_20200225_1906"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_componenets",
                through="course_flow.ComponentCompletionStatus",
                to=settings.AUTH_USER_MODEL,
            ),
        )
    ]
