# Generated by Django 2.2.17 on 2021-03-22 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_flow', '0004_component_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True)),
                ('colour', models.PositiveIntegerField(null=True)),
                ('column_type', models.PositiveIntegerField(choices=[(0, 'Custom Activity Column'), (1, 'Out of Class (Instructor)'), (2, 'Out of Class (Students)'), (3, 'In Class (Instructor)'), (4, 'In Class (Students)'), (10, 'Custom Course Column'), (11, 'Preparation'), (12, 'Lesson'), (13, 'Artifact'), (14, 'Assessment'), (20, 'Custom Program Category')], default=0)),
                ('is_original', models.BooleanField(default=False)),
                ('hash', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent_column', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course_flow.Column')),
            ],
            options={
                'verbose_name': 'Column',
                'verbose_name_plural': 'Columns',
            },
        ),
        migrations.CreateModel(
            name='ColumnWorkflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_flow.Column')),
            ],
            options={
                'verbose_name': 'Column-Workflow Link',
                'verbose_name_plural': 'Column-Workflow Links',
            },
        ),
        migrations.CreateModel(
            name='NodeLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('published', models.BooleanField(default=False)),
                ('source_port', models.PositiveIntegerField(choices=[(1, 'e'), (2, 's'), (3, 'w')], default=2)),
                ('target_port', models.PositiveIntegerField(choices=[(0, 'n'), (1, 'e'), (3, 'w')], default=0)),
                ('dashed', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_original', models.BooleanField(default=True)),
                ('hash', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent_nodelink', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course_flow.NodeLink')),
            ],
            options={
                'verbose_name': 'Node Link',
                'verbose_name_plural': 'Node Links',
            },
        ),
        migrations.CreateModel(
            name='NodeWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('rank', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Node-Week Link',
                'verbose_name_plural': 'Node-Week Links',
            },
        ),
        migrations.CreateModel(
            name='OutcomeOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('rank', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Outcome-Outcome Link',
                'verbose_name_plural': 'Outcome-Outcome Links',
            },
        ),
        migrations.CreateModel(
            name='OutcomeProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('rank', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Outcome-Project Link',
                'verbose_name_plural': 'Outcome-Project Links',
            },
        ),
        migrations.CreateModel(
            name='OutcomeWorkflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('rank', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Outcome-Workflow Link',
                'verbose_name_plural': 'Outcome-Workflow Links',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False)),
                ('is_original', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='WeekWorkflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('rank', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Week-Workflow Link',
                'verbose_name_plural': 'Week-Workflow Links',
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('static', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('is_strategy', models.BooleanField(default=False)),
                ('from_saltise', models.BooleanField(default=False)),
                ('is_original', models.BooleanField(default=True)),
                ('hash', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('outcomes_type', models.PositiveIntegerField(choices=[(0, 'Normal'), (1, 'Advanced')], default=0)),
                ('outcomes_sort', models.PositiveIntegerField(choices=[(0, 'Time'), (1, 'Category'), (2, 'Task'), (3, 'Context')], default=0)),
                ('columns', models.ManyToManyField(blank=True, through='course_flow.ColumnWorkflow', to='course_flow.Column')),
                ('parent_workflow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course_flow.Workflow')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_flow.Project')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_flow.Workflow')),
            ],
            options={
                'verbose_name': 'Workflow-Project Link',
                'verbose_name_plural': 'Workflow-Project Links',
            },
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='outcomes',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='parent_assessment',
        ),
        migrations.RemoveField(
            model_name='component',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='component',
            name='students',
        ),
        migrations.RemoveField(
            model_name='componentcompletionstatus',
            name='component',
        ),
        migrations.RemoveField(
            model_name='componentcompletionstatus',
            name='student',
        ),
        migrations.RemoveField(
            model_name='componentprogram',
            name='component',
        ),
        migrations.RemoveField(
            model_name='componentprogram',
            name='program',
        ),
        migrations.RemoveField(
            model_name='componentweek',
            name='component',
        ),
        migrations.RemoveField(
            model_name='componentweek',
            name='week',
        ),
        migrations.RemoveField(
            model_name='nodestrategy',
            name='node',
        ),
        migrations.RemoveField(
            model_name='nodestrategy',
            name='strategy',
        ),
        migrations.RemoveField(
            model_name='outcomeactivity',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='outcomeactivity',
            name='outcome',
        ),
        migrations.RemoveField(
            model_name='outcomeartifact',
            name='artifact',
        ),
        migrations.RemoveField(
            model_name='outcomeartifact',
            name='outcome',
        ),
        migrations.RemoveField(
            model_name='outcomeassessment',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='outcomeassessment',
            name='outcome',
        ),
        migrations.RemoveField(
            model_name='outcomecourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='outcomecourse',
            name='outcome',
        ),
        migrations.RemoveField(
            model_name='outcomepreparation',
            name='outcome',
        ),
        migrations.RemoveField(
            model_name='outcomepreparation',
            name='preparation',
        ),
        migrations.RemoveField(
            model_name='outcomeprogram',
            name='outcome',
        ),
        migrations.RemoveField(
            model_name='outcomeprogram',
            name='program',
        ),
        migrations.RemoveField(
            model_name='outcomestrategy',
            name='outcome',
        ),
        migrations.RemoveField(
            model_name='outcomestrategy',
            name='strategy',
        ),
        migrations.RemoveField(
            model_name='outcomeweek',
            name='outcome',
        ),
        migrations.RemoveField(
            model_name='outcomeweek',
            name='week',
        ),
        migrations.RemoveField(
            model_name='preparation',
            name='author',
        ),
        migrations.RemoveField(
            model_name='preparation',
            name='outcomes',
        ),
        migrations.RemoveField(
            model_name='preparation',
            name='parent_preparation',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='author',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='nodes',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='outcomes',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='parent_strategy',
        ),
        migrations.RemoveField(
            model_name='strategyactivity',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='strategyactivity',
            name='strategy',
        ),
        migrations.RemoveField(
            model_name='weekcourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='weekcourse',
            name='week',
        ),
        migrations.AlterModelOptions(
            name='week',
            options={'verbose_name': 'Week', 'verbose_name_plural': 'Weeks'},
        ),
        migrations.RemoveField(
            model_name='activity',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='description',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='hash',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='id',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='is_original',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='outcomes',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='parent_activity',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='static',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='strategies',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='title',
        ),
        migrations.RemoveField(
            model_name='course',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='hash',
        ),
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_original',
        ),
        migrations.RemoveField(
            model_name='course',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='course',
            name='outcomes',
        ),
        migrations.RemoveField(
            model_name='course',
            name='parent_course',
        ),
        migrations.RemoveField(
            model_name='course',
            name='static',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title',
        ),
        migrations.RemoveField(
            model_name='course',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='node',
            name='activity_classification',
        ),
        migrations.RemoveField(
            model_name='node',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='node',
            name='work_classification',
        ),
        migrations.RemoveField(
            model_name='program',
            name='components',
        ),
        migrations.RemoveField(
            model_name='program',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='program',
            name='description',
        ),
        migrations.RemoveField(
            model_name='program',
            name='hash',
        ),
        migrations.RemoveField(
            model_name='program',
            name='id',
        ),
        migrations.RemoveField(
            model_name='program',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='program',
            name='outcomes',
        ),
        migrations.RemoveField(
            model_name='program',
            name='title',
        ),
        migrations.RemoveField(
            model_name='week',
            name='components',
        ),
        migrations.RemoveField(
            model_name='week',
            name='outcomes',
        ),
        migrations.AddField(
            model_name='node',
            name='context_classification',
            field=models.PositiveIntegerField(choices=[(0, 'None'), (1, 'Individual Work'), (2, 'Work in Groups'), (3, 'Whole Class'), (101, 'Formative'), (102, 'Summative'), (103, 'Comprehensive')], default=0),
        ),
        migrations.AddField(
            model_name='node',
            name='has_autolink',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='node',
            name='is_dropped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='node',
            name='node_type',
            field=models.PositiveIntegerField(choices=[(0, 'Activity Node'), (1, 'Course Node'), (2, 'Program Node')], default=0),
        ),
        migrations.AddField(
            model_name='node',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='node',
            name='represents_workflow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='node',
            name='task_classification',
            field=models.PositiveIntegerField(choices=[(0, 'None'), (1, 'Gather Information'), (2, 'Discuss'), (3, 'Problem Solve'), (4, 'Analyze'), (5, 'Assess/Review Peers'), (6, 'Debate'), (7, 'Game/Roleplay'), (8, 'Create/Design'), (9, 'Revise/Improve'), (10, 'Read'), (11, 'Write'), (12, 'Present'), (13, 'Experiment/Inquiry'), (14, 'Quiz/Test'), (15, 'Instructor Resource Curation'), (16, 'Instructor Orchestration'), (17, 'Instructor Evaluation'), (18, 'Other'), (101, 'Jigsaw'), (102, 'Peer Instruction'), (103, 'Case Studies'), (104, 'Gallery Walk'), (105, 'Reflective Writing'), (106, 'Two-Stage Exam'), (107, 'Toolkit'), (108, 'One Minute Paper'), (109, 'Distributed Problem Solving'), (110, 'Peer Assessment')], default=0),
        ),
        migrations.AddField(
            model_name='node',
            name='time_required',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='time_units',
            field=models.PositiveIntegerField(choices=[(0, ''), (1, 'seconds'), (2, 'minutes'), (3, 'hours'), (4, 'days'), (5, 'weeks'), (6, 'months'), (7, 'yrs'), (8, 'credits')], default=0),
        ),
        migrations.AddField(
            model_name='outcome',
            name='depth',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outcome',
            name='is_dropped',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='outcome',
            name='is_original',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='outcome',
            name='parent_outcome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course_flow.Outcome'),
        ),
        migrations.AddField(
            model_name='outcome',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outcomenode',
            name='degree',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='week',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='week',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='is_original',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='week',
            name='is_strategy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='week',
            name='parent_week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course_flow.Week'),
        ),
        migrations.AddField(
            model_name='week',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='week',
            name='strategy_classification',
            field=models.PositiveIntegerField(choices=[(0, 'None'), (1, 'Jigsaw'), (2, 'Peer Instruction'), (3, 'Case Studies'), (4, 'Gallery Walk'), (5, 'Reflective Writing'), (6, 'Two-Stage Exam'), (7, 'Toolkit'), (8, 'One Minute Paper'), (9, 'Distributed Problem Solving'), (10, 'Peer Assessment'), (11, 'Other')], default=0),
        ),
        migrations.AddField(
            model_name='week',
            name='week_type',
            field=models.PositiveIntegerField(choices=[(0, 'Part'), (1, 'Week'), (2, 'Term')], default=0),
        ),
        migrations.AlterField(
            model_name='node',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='week',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Artifact',
        ),
        migrations.DeleteModel(
            name='Assessment',
        ),
        migrations.DeleteModel(
            name='Component',
        ),
        migrations.DeleteModel(
            name='ComponentCompletionStatus',
        ),
        migrations.DeleteModel(
            name='ComponentProgram',
        ),
        migrations.DeleteModel(
            name='ComponentWeek',
        ),
        migrations.DeleteModel(
            name='NodeStrategy',
        ),
        migrations.DeleteModel(
            name='OutcomeActivity',
        ),
        migrations.DeleteModel(
            name='OutcomeArtifact',
        ),
        migrations.DeleteModel(
            name='OutcomeAssessment',
        ),
        migrations.DeleteModel(
            name='OutcomeCourse',
        ),
        migrations.DeleteModel(
            name='OutcomePreparation',
        ),
        migrations.DeleteModel(
            name='OutcomeProgram',
        ),
        migrations.DeleteModel(
            name='OutcomeStrategy',
        ),
        migrations.DeleteModel(
            name='OutcomeWeek',
        ),
        migrations.DeleteModel(
            name='Preparation',
        ),
        migrations.DeleteModel(
            name='Strategy',
        ),
        migrations.DeleteModel(
            name='StrategyActivity',
        ),
        migrations.DeleteModel(
            name='WeekCourse',
        ),
        migrations.AddField(
            model_name='workflow',
            name='weeks',
            field=models.ManyToManyField(blank=True, through='course_flow.WeekWorkflow', to='course_flow.Week'),
        ),
        migrations.AddField(
            model_name='weekworkflow',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_flow.Week'),
        ),
        migrations.AddField(
            model_name='weekworkflow',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_flow.Workflow'),
        ),
        migrations.AddField(
            model_name='project',
            name='outcomes',
            field=models.ManyToManyField(blank=True, through='course_flow.OutcomeProject', to='course_flow.Outcome'),
        ),
        migrations.AddField(
            model_name='project',
            name='parent_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course_flow.Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='workflows',
            field=models.ManyToManyField(blank=True, through='course_flow.WorkflowProject', to='course_flow.Workflow'),
        ),
        migrations.AddField(
            model_name='outcomeworkflow',
            name='outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_flow.Outcome'),
        ),
        migrations.AddField(
            model_name='outcomeworkflow',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_flow.Workflow'),
        ),
        migrations.AddField(
            model_name='outcomeproject',
            name='outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_flow.Outcome'),
        ),
        migrations.AddField(
            model_name='outcomeproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_flow.Project'),
        ),
        migrations.AddField(
            model_name='outcomeoutcome',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_outcome_links', to='course_flow.Outcome'),
        ),
        migrations.AddField(
            model_name='outcomeoutcome',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_outcome_links', to='course_flow.Outcome'),
        ),
        migrations.AddField(
            model_name='nodeweek',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_flow.Node'),
        ),
        migrations.AddField(
            model_name='nodeweek',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_flow.Week'),
        ),
        migrations.AddField(
            model_name='nodelink',
            name='source_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='course_flow.Node'),
        ),
        migrations.AddField(
            model_name='nodelink',
            name='target_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='course_flow.Node'),
        ),
        migrations.AddField(
            model_name='columnworkflow',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_flow.Workflow'),
        ),
        migrations.AddField(
            model_name='activity',
            name='workflow_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='course_flow.Workflow'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='workflow_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='course_flow.Workflow'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='column',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='course_flow.Column'),
        ),
        migrations.AddField(
            model_name='node',
            name='linked_workflow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course_flow.Workflow'),
        ),
        migrations.AddField(
            model_name='outcome',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parent_outcomes', through='course_flow.OutcomeOutcome', to='course_flow.Outcome'),
        ),
        migrations.AddField(
            model_name='program',
            name='workflow_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='course_flow.Workflow'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='week',
            name='nodes',
            field=models.ManyToManyField(blank=True, through='course_flow.NodeWeek', to='course_flow.Node'),
        ),
        migrations.AddField(
            model_name='week',
            name='original_strategy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course_flow.Workflow'),
        ),
    ]
