# Generated by Django 2.2.16 on 2020-09-10 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_flow', '0005_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_flow.Activity')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_flow.Column')),
            ],
            options={
                'verbose_name': 'Column-Activity Link',
                'verbose_name_plural': 'Column-Activity Links',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='columns',
            field=models.ManyToManyField(blank=True, through='course_flow.ColumnActivity', to='course_flow.Column'),
        ),
    ]
