# Generated by Django 2.2.16 on 2020-09-16 23:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [("course_flow", "0005_auto_20200916_1732")]

    operations = [
        migrations.CreateModel(
            name="ColumnWorkflow",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_on", models.DateTimeField(auto_now_add=True)),
                ("rank", models.PositiveIntegerField(default=0)),
                (
                    "column",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course_flow.Column",
                    ),
                ),
            ],
            options={
                "verbose_name": "Column-Workflow Link",
                "verbose_name_plural": "Column-Workflow Links",
            },
        ),
        migrations.CreateModel(
            name="OutcomeWorkflow",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_on", models.DateTimeField(auto_now_add=True)),
                ("rank", models.PositiveIntegerField(default=0)),
                (
                    "outcome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course_flow.Outcome",
                    ),
                ),
            ],
            options={
                "verbose_name": "Outcome-Workflow Link",
                "verbose_name_plural": "Outcome-Workflow Links",
            },
        ),
        migrations.CreateModel(
            name="StrategyWorkflow",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_on", models.DateTimeField(auto_now_add=True)),
                ("rank", models.PositiveIntegerField(default=0)),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course_flow.Strategy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Strategy-Workflow Link",
                "verbose_name_plural": "Strategy-Workflow Links",
            },
        ),
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("description", models.TextField(max_length=400)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("static", models.BooleanField(default=False)),
                ("is_original", models.BooleanField(default=True)),
                (
                    "hash",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "columns",
                    models.ManyToManyField(
                        blank=True,
                        through="course_flow.ColumnWorkflow",
                        to="course_flow.Column",
                    ),
                ),
                (
                    "outcomes",
                    models.ManyToManyField(
                        blank=True,
                        through="course_flow.OutcomeWorkflow",
                        to="course_flow.Outcome",
                    ),
                ),
                (
                    "parent_activity",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="course_flow.Activity",
                    ),
                ),
                (
                    "strategies",
                    models.ManyToManyField(
                        blank=True,
                        through="course_flow.StrategyWorkflow",
                        to="course_flow.Strategy",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="strategyworkflow",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="course_flow.Workflow",
            ),
        ),
        migrations.AddField(
            model_name="outcomeworkflow",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="course_flow.Workflow",
            ),
        ),
        migrations.AddField(
            model_name="columnworkflow",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="course_flow.Workflow",
            ),
        ),
    ]
