# Generated by Django 2.2.16 on 2020-09-17 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("course_flow", "0007_auto_20200916_2323")]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
            },
        ),
        migrations.AlterField(
            model_name="activity",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="authored_activities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
