# Generated by Django 2.2.16 on 2020-09-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("course_flow", "0012_auto_20200930_1845")]

    operations = [
        migrations.RemoveField(model_name="assessment", name="author"),
        migrations.RemoveField(model_name="assessment", name="outcomes"),
        migrations.RemoveField(
            model_name="assessment", name="parent_assessment"
        ),
        migrations.RemoveField(model_name="component", name="content_type"),
        migrations.RemoveField(model_name="component", name="students"),
        migrations.RemoveField(
            model_name="componentcompletionstatus", name="component"
        ),
        migrations.RemoveField(
            model_name="componentcompletionstatus", name="student"
        ),
        migrations.RemoveField(model_name="componentweek", name="component"),
        migrations.RemoveField(model_name="componentweek", name="week"),
        migrations.RemoveField(model_name="outcomeartifact", name="artifact"),
        migrations.RemoveField(model_name="outcomeartifact", name="outcome"),
        migrations.RemoveField(
            model_name="outcomeassessment", name="assessment"
        ),
        migrations.RemoveField(model_name="outcomeassessment", name="outcome"),
        migrations.RemoveField(
            model_name="outcomepreparation", name="outcome"
        ),
        migrations.RemoveField(
            model_name="outcomepreparation", name="preparation"
        ),
        migrations.RemoveField(model_name="outcomeweek", name="outcome"),
        migrations.RemoveField(model_name="outcomeweek", name="week"),
        migrations.RemoveField(model_name="preparation", name="author"),
        migrations.RemoveField(model_name="preparation", name="outcomes"),
        migrations.RemoveField(
            model_name="preparation", name="parent_preparation"
        ),
        migrations.RemoveField(model_name="week", name="author"),
        migrations.RemoveField(model_name="week", name="components"),
        migrations.RemoveField(model_name="week", name="outcomes"),
        migrations.AlterField(
            model_name="node",
            name="description",
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="node",
            name="title",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="description",
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="title",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="description",
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="title",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.DeleteModel(name="Artifact"),
        migrations.DeleteModel(name="Assessment"),
        migrations.DeleteModel(name="Component"),
        migrations.DeleteModel(name="ComponentCompletionStatus"),
        migrations.DeleteModel(name="ComponentWeek"),
        migrations.DeleteModel(name="OutcomeArtifact"),
        migrations.DeleteModel(name="OutcomeAssessment"),
        migrations.DeleteModel(name="OutcomePreparation"),
        migrations.DeleteModel(name="OutcomeWeek"),
        migrations.DeleteModel(name="Preparation"),
        migrations.DeleteModel(name="Week"),
    ]
