# Generated by Django 2.2.16 on 2020-10-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("course_flow", "0017_nodelink")]

    operations = [
        migrations.AddField(
            model_name="node",
            name="has_autolink",
            field=models.BooleanField(default=False),
        )
    ]
