# Generated by Django 2.2.16 on 2020-10-29 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_flow', '0019_auto_20201016_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='WorkflowProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_flow.Project')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_flow.Workflow')),
            ],
            options={
                'verbose_name': 'Workflow-Project Link',
                'verbose_name_plural': 'Workflow-Project Links',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='workflows',
            field=models.ManyToManyField(blank=True, through='course_flow.WorkflowProject', to='course_flow.Workflow'),
        ),
    ]
