# Generated by Django 2.2.16 on 2020-10-30 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("course_flow", "0020_auto_20201029_2053")]

    operations = [
        migrations.AddField(
            model_name="node",
            name="linked_workflow",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="course_flow.Workflow",
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="represents_workflow",
            field=models.BooleanField(default=False),
        ),
    ]
