# Generated by Django 2.2.16 on 2020-11-02 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("course_flow", "0021_auto_20201030_1739")]

    operations = [
        migrations.AddField(
            model_name="nodelink",
            name="is_original",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="nodelink",
            name="parent_nodelink",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="course_flow.NodeLink",
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="published",
            field=models.BooleanField(default=False),
        ),
    ]
