# Generated by Django 2.2.16 on 2020-11-02 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("course_flow", "0022_auto_20201102_2149")]

    operations = [
        migrations.AddField(
            model_name="column",
            name="is_original",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="column",
            name="parent_column",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="course_flow.Column",
            ),
        ),
    ]
