# Generated by Django 2.2.16 on 2020-11-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_flow', '0024_auto_20201103_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
