# Generated by Django 2.2.16 on 2020-11-18 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_flow', '0025_column_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='activity_classification',
        ),
        migrations.RemoveField(
            model_name='node',
            name='work_classification',
        ),
        migrations.AddField(
            model_name='node',
            name='context_classification',
            field=models.PositiveIntegerField(choices=[(0, 'None'), (1, 'Individual Work'), (2, 'Work in Groups'), (3, 'Whole Class')], default=0),
        ),
        migrations.AddField(
            model_name='node',
            name='task_classification',
            field=models.PositiveIntegerField(choices=[(0, 'None'), (1, 'Gather Information'), (2, 'Discuss'), (3, 'Problem Solve'), (4, 'Analyze'), (5, 'Assess/Review Peers'), (6, 'Debate'), (7, 'Game/Roleplay'), (8, 'Create/Design'), (9, 'Revise/Improve'), (10, 'Read'), (11, 'Write'), (12, 'Present'), (13, 'Experiment/Inquiry'), (14, 'Quiz/Test'), (15, 'Instructor Resource Curation'), (16, 'Instructor Orchestration'), (17, 'Instructor Evaluation'), (18, 'Other')], default=0),
        ),
        migrations.AlterField(
            model_name='node',
            name='column',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='course_flow.Column'),
        ),
    ]
