# Generated by Django 2.2.16 on 2020-11-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_flow', '0026_auto_20201118_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='is_dropped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='node',
            name='time_required',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='time_units',
            field=models.PositiveIntegerField(choices=[(0, ''), (1, 'seconds'), (2, 'minutes'), (3, 'hours'), (4, 'days'), (5, 'weeks'), (6, 'months'), (7, 'yrs'), (8, 'credits')], default=0),
        ),
    ]
