# Generated by Django 2.2.16 on 2021-01-04 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_flow', '0027_auto_20201118_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcome',
            name='depth',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='node',
            name='context_classification',
            field=models.PositiveIntegerField(choices=[(0, 'None'), (1, 'Individual Work'), (2, 'Work in Groups'), (3, 'Whole Class'), (101, 'Formative'), (102, 'Summative'), (103, 'Comprehensive')], default=0),
        ),
        migrations.AlterField(
            model_name='node',
            name='task_classification',
            field=models.PositiveIntegerField(choices=[(0, 'None'), (1, 'Gather Information'), (2, 'Discuss'), (3, 'Problem Solve'), (4, 'Analyze'), (5, 'Assess/Review Peers'), (6, 'Debate'), (7, 'Game/Roleplay'), (8, 'Create/Design'), (9, 'Revise/Improve'), (10, 'Read'), (11, 'Write'), (12, 'Present'), (13, 'Experiment/Inquiry'), (14, 'Quiz/Test'), (15, 'Instructor Resource Curation'), (16, 'Instructor Orchestration'), (17, 'Instructor Evaluation'), (18, 'Other'), (101, 'Jigsaw'), (102, 'Peer Instruction'), (103, 'Case Studies'), (104, 'Gallery Walk'), (105, 'Reflective Writing'), (106, 'Two-Stage Exam'), (107, 'Toolkit'), (108, 'One Minute Paper'), (109, 'Distributed Problem Solving'), (110, 'Peer Assessment')], default=0),
        ),
        migrations.AlterField(
            model_name='nodelink',
            name='is_original',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='title',
            field=models.CharField(max_length=400),
        ),
        migrations.CreateModel(
            name='OutcomeOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('children', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_outcome_links', to='course_flow.Outcome')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_outcome_links', to='course_flow.Outcome')),
            ],
            options={
                'verbose_name': 'Outcome-Outcome Link',
                'verbose_name_plural': 'Outcome-Outcome Links',
            },
        ),
    ]
