# Generated by Django 2.2.16 on 2021-01-04 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_flow', '0028_auto_20210104_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutcomeProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_flow.Outcome')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_flow.Project')),
            ],
            options={
                'verbose_name': 'Outcome-Project Link',
                'verbose_name_plural': 'Outcome-Project Links',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='outcomes',
            field=models.ManyToManyField(blank=True, through='course_flow.OutcomeProject', to='course_flow.Outcome'),
        ),
    ]
