# Generated by Django 2.2.16 on 2021-01-04 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_flow', '0029_auto_20210104_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outcomeoutcome',
            old_name='children',
            new_name='child',
        ),
    ]
