# Generated by Django 2.2.16 on 2021-01-05 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_flow', '0030_auto_20210104_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='outcomes',
        ),
        migrations.AddField(
            model_name='outcome',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parent_outcomes', through='course_flow.OutcomeOutcome', to='course_flow.Outcome'),
        ),
        migrations.AddField(
            model_name='outcome',
            name='is_original',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='outcome',
            name='parent_outcome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course_flow.Outcome'),
        ),
    ]
