# Generated by Django 2.2.16 on 2021-01-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_flow', '0031_auto_20210105_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcome',
            name='is_dropped',
            field=models.BooleanField(default=True),
        ),
    ]
