# Generated by Django 2.2.16 on 2021-01-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_flow', '0032_outcome_is_dropped'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='outcomes_type',
            field=models.PositiveIntegerField(choices=[(0, 'Normal'), (1, 'Advanced')], default=0),
        ),
    ]
