# Generated by Django 2.2.16 on 2021-01-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_flow', '0033_workflow_outcomes_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcomenode',
            name='degree',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
