# Generated by Django 2.2.16 on 2021-01-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_flow', '0034_outcomenode_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='outcomes_sort',
            field=models.PositiveIntegerField(choices=[(0, 'Time'), (1, 'Category'), (2, 'Task'), (3, 'Context')], default=0),
        ),
    ]
