# Generated by Django 2.2.16 on 2021-01-19 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_flow', '0035_workflow_outcomes_sort'),
    ]

    operations = [
        migrations.RenameModel("Strategy","Week"),
        migrations.RenameModel(
            old_name='NodeStrategy',
            new_name='NodeWeek',
        ),
        migrations.RenameModel(
            old_name='OutcomeStrategy',
            new_name='OutcomeWeek',
        ),
        migrations.RenameModel(
            old_name='StrategyWorkflow',
            new_name='WeekWorkflow',
        ),
        migrations.RenameField("Week","strategy_type","week_type"),
        migrations.RenameField("Week","parent_strategy","parent_week"),
        migrations.RenameField("Workflow","strategies","weeks"),
        migrations.RenameField("NodeWeek","strategy","week"),
        migrations.RenameField("WeekWorkflow","strategy","week"),
        migrations.RenameField("OutcomeWeek","strategy","week"),
        migrations.AlterModelOptions(
            name='nodeweek',
            options={'verbose_name': 'Node-Week Link', 'verbose_name_plural': 'Node-Week Links'},
        ),
        migrations.AlterModelOptions(
            name='outcomeweek',
            options={'verbose_name': 'Outcome-Week Link', 'verbose_name_plural': 'Outcome-Week Links'},
        ),
        migrations.AlterModelOptions(
            name='weekworkflow',
            options={'verbose_name': 'Week-Workflow Link', 'verbose_name_plural': 'Week-Workflow Links'},
        ),
        
        
    ]
