# Generated by Django 2.2.16 on 2021-01-19 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_flow', '0036_auto_20210119_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='week',
            options={'verbose_name': 'Week', 'verbose_name_plural': 'Weeks'},
        ),
    ]
