# Generated by Django 2.2.16 on 2021-01-19 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_flow', '0037_auto_20210119_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeStrategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_flow.Node')),
            ],
            options={
                'verbose_name': 'Node-Strategy Link',
                'verbose_name_plural': 'Node-Strategy Links',
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, max_length=400, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('default', models.BooleanField(default=False)),
                ('is_original', models.BooleanField(default=True)),
                ('published', models.BooleanField(default=False)),
                ('hash', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('nodes', models.ManyToManyField(blank=True, through='course_flow.NodeStrategy', to='course_flow.Node')),
                ('parent_strategy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course_flow.Strategy')),
            ],
            options={
                'verbose_name': 'Strategy',
                'verbose_name_plural': 'Strategies',
            },
        ),
        migrations.DeleteModel(
            name='OutcomeWeek',
        ),
        migrations.AddField(
            model_name='nodestrategy',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_flow.Strategy'),
        ),
    ]
