# Generated by Django 2.2.16 on 2021-01-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_flow', '0038_auto_20210119_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='author',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='nodes',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='parent_strategy',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='outcomes',
        ),
        migrations.AddField(
            model_name='workflow',
            name='is_strategy',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='NodeStrategy',
        ),
        migrations.DeleteModel(
            name='Strategy',
        ),
    ]
