# Generated by Django 2.2.16 on 2021-01-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_flow', '0039_auto_20210120_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='is_strategy',
            field=models.BooleanField(default=False),
        ),
    ]
