# Generated by Django 2.2.16 on 2021-01-22 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_flow', '0040_week_is_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='original_strategy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course_flow.Workflow'),
        ),
    ]
