# Generated by Django 2.2.16 on 2021-01-28 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_flow', '0041_week_original_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='from_saltise',
            field=models.BooleanField(default=False),
        ),
    ]
