# Generated by Django 2.2.16 on 2021-01-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_flow', '0042_workflow_from_saltise'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='strategy_classification',
            field=models.PositiveIntegerField(choices=[(0, 'None'), (1, 'Jigsaw'), (2, 'Peer Instruction'), (3, 'Case Studies'), (4, 'Gallery Walk'), (5, 'Reflective Writing'), (6, 'Two-Stage Exam'), (7, 'Toolkit'), (8, 'One Minute Paper'), (9, 'Distributed Problem Solving'), (10, 'Peer Assessment')], default=0),
        ),
        migrations.AlterField(
            model_name='node',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
