# Generated by Django 2.2.16 on 2021-01-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_flow', '0043_auto_20210129_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='strategy_classification',
            field=models.PositiveIntegerField(choices=[(0, 'None'), (1, 'Jigsaw'), (2, 'Peer Instruction'), (3, 'Case Studies'), (4, 'Gallery Walk'), (5, 'Reflective Writing'), (6, 'Two-Stage Exam'), (7, 'Toolkit'), (8, 'One Minute Paper'), (9, 'Distributed Problem Solving'), (10, 'Peer Assessment'), (11, 'Other')], default=0),
        ),
    ]
