# Generated by Django 2.2.16 on 2021-03-15 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_flow', '0046_column_colour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='discipline',
        ),
        migrations.AddField(
            model_name='project',
            name='discipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course_flow.Discipline'),
        ),
    ]
