# Generated by Django 3.2 on 2022-09-01 19:08

import course_flow.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_flow', '0087_auto_20220704_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_reporting', models.BooleanField(default=True)),
                ('single_completion', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=course_flow.models.default_due_date)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('linked_workflows', models.ManyToManyField(blank=True, to='course_flow.Workflow')),
            ],
        ),
        migrations.CreateModel(
            name='LiveProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(default=False)),
                ('default_self_reporting', models.BooleanField(default=True)),
                ('default_assign_to_all', models.BooleanField(default=True)),
                ('default_single_completion', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course_flow.project')),
            ],
        ),
        migrations.CreateModel(
            name='LiveUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.PositiveIntegerField(choices=[(0, 'Student'), (1, 'Teacher')], default=0)),
                ('live_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_flow.liveproject')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_flow.liveassignment')),
                ('live_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_flow.liveuser')),
            ],
        ),
        migrations.AddField(
            model_name='liveproject',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='live_projects_added', through='course_flow.LiveUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='liveproject',
            name='visible_workflows',
            field=models.ManyToManyField(blank=True, to='course_flow.Workflow'),
        ),
        migrations.AddField(
            model_name='liveassignment',
            name='live_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_flow.liveproject'),
        ),
        migrations.AddField(
            model_name='liveassignment',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='course_flow.Node'),
        ),
    ]
