# Generated by Django 3.2 on 2022-09-01 19:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course_flow', '0088_auto_20220901_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveproject',
            name='deleted_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
