# Generated by Django 3.2.14 on 2022-09-09 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('course_flow', '0089_liveproject_deleted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ['project', 'activity', 'course', 'program', 'liveproject']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
