# Generated by Django 3.2.15 on 2023-02-06 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('course_flow', '0107_alter_objectpermission_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectpermission',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ['project', 'workflow']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
