# Generated by Django 3.2.15 on 2023-02-19 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("course_flow", "0110_alter_favourite_content_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favourite",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to={"model__in": ["project", "workflow"]},
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
