# Generated by Django 3.2.16 on 2023-12-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course_flow", "0117_alter_notification_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseflowuser",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("fr", "French")],
                default="en",
                max_length=2,
            ),
        ),
    ]
