# Generated by Django 3.2.23 on 2024-01-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course_flow", "0118_courseflowuser_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseflowuser",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("fr", "French")],
                default="en",
                max_length=2,
                verbose_name="Language preferences",
            ),
        ),
    ]
